import {
  DataTypes,
  Model,
} from "sequelize";

import type {
  Optional,
} from "sequelize";

import sequelize from "./database.js";

/*
  This describes all columns
  inside the projects table.
*/
interface ProjectAttributes {
  id: number;
  userId: number;
  name: string;
  description: string | null;
  createdAt?: Date;
  updatedAt?: Date;
}

/*
  These fields are optional
  when creating a new project.

  id is generated by PostgreSQL.

  createdAt and updatedAt are
  generated automatically by Sequelize.
*/
interface ProjectCreationAttributes
  extends Optional<
    ProjectAttributes,
    "id" | "description" | "createdAt" | "updatedAt"
  > {}

/*
  This creates the Sequelize Project model.
*/
class Project
  extends Model<
    ProjectAttributes,
    ProjectCreationAttributes
  >
  implements ProjectAttributes
{
  public id!: number;

  /*
    Foreign key that connects this project
    to the user who owns it.
  */
  public userId!: number;

  public name!: string;

  public description!: string | null;

  public readonly createdAt!: Date;

  public readonly updatedAt!: Date;
}

/*
  Defines how the Project model maps
  to the PostgreSQL projects table.
*/
Project.init(
  {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },

    userId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      field: "user_id",
    },

    name: {
      type: DataTypes.STRING(60),
      allowNull: false,
    },

    description: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
  },
  {
    sequelize,

    /*
      Actual table name in PostgreSQL.
    */
    tableName: "projects",

    /*
      Sequelize automatically manages:
      createdAt
      updatedAt
    */
    timestamps: true,

    /*
      Makes Sequelize use snake_case
      column names such as:
      created_at
      updated_at
    */
    underscored: true,
  }
);

export default Project;