import {
  DataTypes,
  Model,
} from "sequelize";

import type {
  Optional,
} from "sequelize";

import sequelize from "./database.js";

/*
  These are the only allowed task statuses.
*/
type TaskStatus =
  | "To Do"
  | "In Progress"
  | "Done";

/*
  These are the only allowed task priorities.
*/
type TaskPriority =
  | "Low"
  | "Medium"
  | "High";

/*
  This describes all columns
  inside the tasks table.
*/
interface TaskAttributes {
  id: number;

  /*
    Foreign key that connects this task
    to the project it belongs to.
  */
  projectId: number;

  title: string;
  description: string | null;
  status: TaskStatus;
  priority: TaskPriority;
  estimatedMinutes: number | null;
  dueDate: Date | null;
  createdAt?: Date;
  updatedAt?: Date;
}

/*
  These fields are optional when creating a task.

  id is generated by PostgreSQL.

  description, estimatedMinutes and dueDate
  are optional fields.

  createdAt and updatedAt are handled
  automatically by Sequelize.
*/
interface TaskCreationAttributes
  extends Optional<
    TaskAttributes,
    | "id"
    | "description"
    | "estimatedMinutes"
    | "dueDate"
    | "createdAt"
    | "updatedAt"
  > {}

/*
  This creates the Sequelize Task model.
*/
class Task
  extends Model<
    TaskAttributes,
    TaskCreationAttributes
  >
  implements TaskAttributes
{
  public id!: number;

  /*
    Foreign key to projects.id.
  */
  public projectId!: number;

  public title!: string;
  public description!: string | null;
  public status!: TaskStatus;
  public priority!: TaskPriority;
  public estimatedMinutes!: number | null;
  public dueDate!: Date | null;

  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;
}

/*
  Defines how the Task model maps
  to the PostgreSQL tasks table.
*/
Task.init(
  {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },

    projectId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      field: "project_id",
    },

    title: {
      type: DataTypes.STRING(100),
      allowNull: false,
    },

    description: {
      type: DataTypes.TEXT,
      allowNull: true,
    },

    status: {
      type: DataTypes.ENUM(
        "To Do",
        "In Progress",
        "Done"
      ),
      allowNull: false,
      defaultValue: "To Do",
    },

    priority: {
      type: DataTypes.ENUM(
        "Low",
        "Medium",
        "High"
      ),
      allowNull: false,
      defaultValue: "Medium",
    },

    estimatedMinutes: {
      type: DataTypes.INTEGER,
      allowNull: true,
      field: "estimated_minutes",
    },

    dueDate: {
      type: DataTypes.DATEONLY,
      allowNull: true,
      field: "due_date",
    },
  },
  {
    sequelize,
    tableName: "tasks",
    timestamps: true,
    underscored: true,
  }
);

export default Task;