import {
  DataTypes,
  Model,
} from "sequelize";

import type {
  Optional,
} from "sequelize";

import sequelize from "./database.js";

/*
  This describes all columns
  inside the time_entries table.
*/
interface TimeEntryAttributes {
  id: number;

  /*
    Foreign key connecting this time entry
    to the task it belongs to.
  */
  taskId: number;

  /*
    Time is stored in PostgreSQL
    as minutes.

    Example:
    1 hour = 60 minutes
    1.5 hours = 90 minutes
  */
  durationMinutes: number;

  /*
    Date when the work was done.
  */
  date: string;

  /*
    Optional note about the work completed.
  */
  note: string | null;

  createdAt?: Date;
  updatedAt?: Date;
}

/*
  These fields are optional
  when creating a new time entry.

  id is generated by PostgreSQL.

  note is optional.

  createdAt and updatedAt are
  managed automatically by Sequelize.
*/
interface TimeEntryCreationAttributes
  extends Optional<
    TimeEntryAttributes,
    | "id"
    | "note"
    | "createdAt"
    | "updatedAt"
  > {}

/*
  Creates the Sequelize TimeEntry model.
*/
class TimeEntry
  extends Model<
    TimeEntryAttributes,
    TimeEntryCreationAttributes
  >
  implements TimeEntryAttributes
{
  declare id: number;

  /*
    Foreign key to tasks.id.
  */
  declare taskId: number;

  /*
    Stored in PostgreSQL as minutes.
  */
  declare durationMinutes: number;

  /*
    Date when the work was done.
  */
  declare date: string;

  /*
    Optional note.
  */
  declare note: string | null;

  /*
    Sequelize creates these automatically
    because timestamps is enabled.
  */
  declare readonly createdAt: Date;

  declare readonly updatedAt: Date;
}

/*
  Maps the model to the
  PostgreSQL time_entries table.
*/
TimeEntry.init(
  {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },

    taskId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      field: "task_id",
    },

    durationMinutes: {
      type: DataTypes.INTEGER,
      allowNull: false,
      field: "duration_minutes",
    },

    date: {
      type: DataTypes.DATEONLY,
      allowNull: false,
    },

    note: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
  },
  {
    sequelize,
    tableName: "time_entries",
    timestamps: true,
    underscored: true,
  }
);

export default TimeEntry;